/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: {
          DEFAULT: 'var(--color-bg)',
          subtle: 'var(--color-bg-subtle)',
          muted: 'var(--color-bg-muted)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          overlay: 'var(--color-surface-overlay)',
          'overlay-strong': 'var(--color-surface-overlay-strong)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
          'inverse-secondary': 'var(--color-text-inverse-secondary)',
          link: 'var(--color-text-link)',
          'link-hover': 'var(--color-text-link-hover)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
          focus: 'var(--color-border-focus)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          subtle: 'var(--color-accent-subtle)',
          muted: 'var(--color-accent-muted)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          subtle: 'var(--color-success-subtle)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          subtle: 'var(--color-warning-subtle)',
        },
        danger: {
          DEFAULT: 'var(--color-danger)',
          subtle: 'var(--color-danger-subtle)',
        },
      },
      borderRadius: {
        sm: '10px',
        DEFAULT: '14px',
        md: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        pill: '999px',
      },
      boxShadow: {
        xs: '0 1px 2px var(--shadow-color-subtle)',
        sm: '0 1px 3px var(--shadow-color), 0 1px 2px var(--shadow-color-subtle)',
        DEFAULT: '0 4px 6px -1px var(--shadow-color), 0 2px 4px -2px var(--shadow-color-subtle)',
        md: '0 6px 12px -3px var(--shadow-color), 0 4px 6px -4px var(--shadow-color-subtle)',
        lg: '0 10px 20px -5px var(--shadow-color), 0 6px 10px -6px var(--shadow-color-subtle)',
        glow: '0 0 0 3px var(--color-border-focus)',
        'card-hover': '0 8px 24px -4px var(--shadow-color), 0 4px 8px -3px var(--shadow-color-subtle)',
      },
      blur: {
        header: '12px',
        popover: '16px',
        modal: '24px',
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '15': '3.75rem',
        '18': '4.5rem',
        '22': '5.5rem',
      },
      transitionDuration: {
        fast: '120ms',
        normal: '180ms',
        slow: '240ms',
      },
      animation: {
        'fade-in': 'fadeIn 180ms ease-out',
        'fade-out': 'fadeOut 120ms ease-in',
        'slide-up': 'slideUp 200ms ease-out',
        'slide-down': 'slideDown 200ms ease-out',
        'scale-in': 'scaleIn 180ms ease-out',
        'toast-in': 'toastIn 200ms ease-out',
        'toast-out': 'toastOut 150ms ease-in forwards',
        'slide-right-in': 'slideRightIn 200ms ease-out',
        'slide-left-in': 'slideLeftIn 200ms ease-out',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeOut: { from: { opacity: '1' }, to: { opacity: '0' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.96)' }, to: { opacity: '1', transform: 'scale(1)' } },
        toastIn: { from: { opacity: '0', transform: 'translateY(12px) scale(0.97)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        toastOut: { from: { opacity: '1', transform: 'translateY(0) scale(1)' }, to: { opacity: '0', transform: 'translateY(-8px) scale(0.97)' } },
        slideRightIn: { from: { opacity: '0', transform: 'translateX(100%)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideLeftIn: { from: { opacity: '0', transform: 'translateX(-100%)' }, to: { opacity: '1', transform: 'translateX(0)' } },
      },
      zIndex: {
        base: '1',
        dropdown: '100',
        sticky: '200',
        overlay: '400',
        modal: '500',
        toast: '600',
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem' }],
        xs: ['0.75rem', { lineHeight: '1.125rem' }],
        sm: ['0.875rem', { lineHeight: '1.375rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.625rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.15' }],
      },
      maxWidth: {
        content: '1120px',
        'content-wide': '1280px',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
